account/urls.py
from django.urls import path

from . import views

app_name = "account"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("oauth/start", views.start_login, name="oauth_start"),
    path("oauth/authorize", views.finish_login, name="oauth_finish"),
    path("settings", views.settings, name="settings"),
    path("logout", views.logout_view, name="logout"),
]

conversations/urls.py
from django.urls import path

from . import views

app_name = "conversations"
urlpatterns = [
    path("", views.index, name="index"),
    path("send", views.send, name="send"),
    path("<str:name>", views.index, name="category"),
    path("threads/<int:pk>", views.ThreadView.as_view(), name="thread"),
    path("threads/<int:pk>/reply", views.reply, name="reply"),
    path("threads/<int:pk>/assign", views.claim, name="claim"),
    path("threads/<int:pk>/unassign", views.unclaim, name="unclaim"),
    path("threads/<int:pk>/toggle", views.toggle_unread, name="toggle_unread"),
    path(
        "threads/<int:pk>/change-category",
        views.change_category,
        name="change_category",
    ),
    path("threads/<int:pk>/delete", views.delete, name="delete"),
]

mailgunner/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from . import views

urlpatterns = [
    # Home page
    path("", views.index, name="index"),
    # user authentication
    path("account/", include("account.urls")),
    # conversations mail
    path("conversations/", include("conversations.urls")),
    # schedule mail
    path("schedule/", include("schedule.urls")),
    # Routes from other packages
    path("admin/", admin.site.urls),
    re_path(r"^webhooks/", include("anymail.urls")),
]

schedule/urls.py
from django.urls import path

from . import views

app_name = "schedule"
urlpatterns = [
    path("", views.QueuedView.as_view(), name="queued"),
    path("sent", views.SentView.as_view(), name="sent"),
    path("new", views.new, name="new"),
    path("messages/<int:pk>", views.MessageView.as_view(), name="message"),
    path("messages/<int:pk>/delete", views.delete, name="delete"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>MailGunner | {% block title %}{% endblock %}</title>

    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <style>
        body {
            padding-top: 5rem;
        }
    </style>

    <!-- Toastr.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous"></script>

    <!-- Feather Icons -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.28.0/feather.min.js" integrity="sha512-7x3zila4t2qNycrtZ31HO0NnJr8kg2VI67YLoRSyi9hGhRN66FHYWr7Axa9Y1J9tGYHVBPqIjSE1ogHrJTz51g==" crossorigin="anonymous"></script>

    {% block custom-css %}{% endblock %}
    {% block custom-js %}{% endblock %}
</head>
<body style="background-color: #e8e8e8">
    {% include "navbar.html" %}

    <main class="container">
        {% include "messages.html" %}

        {% block content %}{% endblock %}
    </main>

    <!-- Bootstrap 5 JS (w/ Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-md-2 g-4">
    <div class="col">
        <div class="card shadow rounded">
            <h3 class="card-header">Conversations</h3>
            <div class="card-body">
                <div class="row text-center m-0 p-0">
                    <div class="col-md">
                        <a href="{% url 'conversations:index' %}">Inbox</a>
                    </div>
                    <div class="col-md">
                        <a href="{% url 'conversations:send' %}">New Thread</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card shadow rounded">
            <h3 class="card-header">Schedule Mail</h3>
            <div class="card-body">
                <div class="row text-center m-0 p-0">
                    <div class="col-md">
                        <a href="{% url 'schedule:queued' %}">Queued Messages</a>
                    </div>
                    <div class="col-md">
                        <a href="{% url 'schedule:new' %}">Schedule Message</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card shadow rounded">
            <h3 class="card-header">Your Account</h3>
            <div class="card-body">
                <div class="row text-center m-0 p-0">
                    {% if user.is_staff %}
                        <div class="col-md">
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </div>
                    {% endif %}
                    <div class="col-md">
                        <a href="{% url 'account:settings' %}">Settings</a>
                    </div>
                    <div class="col-md">
                        <a href="{% url 'account:logout' %}">Logout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}
            <div class="alert alert-{{ message.tags|lower }}">{{ message }}</div>
        {% else %}
            <div class="alert alert-info">{{ message }}</div>
        {% endif %}
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">MailGunner</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'conversations:index' %}">Conversations</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'schedule:queued' %}">Schedule</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navDropdownToggle" data-bs-toggle="dropdown" aria-expanded="false">{{ user.profile.preferred_username }}</a>
                    <ul class="dropdown-menu" aria-labelledby="navDropdownToggle">
                        {% if user.is_staff %}<li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>{% endif%}
                        <li><a class="dropdown-item" href="{% url 'account:settings' %}">Settings</a></li>
                        <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>