account/urls.py
from django.urls import path

from . import views

app_name = "account"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("oauth/start", views.start_login, name="oauth_start"),
    path("oauth/authorize", views.finish_login, name="oauth_finish"),
    path("settings", views.settings, name="settings"),
    path("logout", views.logout_view, name="logout"),
]

conversations/urls.py
from django.urls import path

from . import views

app_name = "conversations"
urlpatterns = [
    path("", views.index, name="index"),
    path("send", views.send, name="send"),
    path("<str:name>", views.index, name="category"),
    path("threads/<int:pk>", views.ThreadView.as_view(), name="thread"),
    path("threads/<int:pk>/reply", views.reply, name="reply"),
    path("threads/<int:pk>/assign", views.claim, name="claim"),
    path("threads/<int:pk>/unassign", views.unclaim, name="unclaim"),
    path("threads/<int:pk>/toggle", views.toggle_unread, name="toggle_unread"),
    path(
        "threads/<int:pk>/change-category",
        views.change_category,
        name="change_category",
    ),
    path("threads/<int:pk>/delete", views.delete, name="delete"),
]

mailgunner/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from . import views

urlpatterns = [
    # Home page
    path("", views.index, name="index"),
    # user authentication
    path("account/", include("account.urls")),
    # conversations mail
    path("conversations/", include("conversations.urls")),
    # schedule mail
    path("schedule/", include("schedule.urls")),
    # Routes from other packages
    path("admin/", admin.site.urls),
    re_path(r"^webhooks/", include("anymail.urls")),
]

conversations/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy
from django_better_admin_arrayfield.models.fields import ArrayField
from os import path
from uuid import uuid4


class Category(models.Model):
    """
    A collection of threads linked by recipient email
    """

    # The name of the category
    name = models.CharField(max_length=256)

    # The address corresponding to the field
    addresses = ArrayField(models.EmailField(), blank=True)

    def __str__(self):
        return self.name


class Thread(models.Model):
    """
    A chain of replies for messages linked by the 'References', 'Message-Id', and 'In-Reply-To' headers
    """

    # Who the thread is assigned to
    assignee = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, blank=True, null=True
    )

    # The category the message is in
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=True, null=True
    )

    # The subject line of the original message
    subject = models.CharField(max_length=255)

    # When the thread last got a message
    last_updated = models.DateTimeField()

    # Who the message was originally from (ignores replies)
    originally_from = models.CharField(max_length=510)

    # Who the message was originally to (ignores replies)
    recipient = models.EmailField()

    # Whether the are any parts of the thread that are unread
    unread = models.BooleanField()

    def __str__(self):
        return f'<Thread pk={self.pk} originally_from="{self.originally_from}" last_updated="{self.recipient}"'

    def is_older_than_a_day(self):
        """
        Whether the message is older than a day
        """
        difference = timezone.now() - self.last_updated
        return difference.days >= 1

    class Meta:
        ordering = ["-last_updated"]


class MessageType(models.IntegerChoices):
    """
    The type of message
    """

    INCOMING = 0
    OUTGOING = 1


class MessageStatus(models.IntegerChoices):
    """
    The status of the message as reported by MailGun
    """

    PENDING = 0, gettext_lazy("Waiting to send...")
    SENT = 1, gettext_lazy("Successfully sent")
    FAILED = 2, gettext_lazy("Failed to send")

    __empty__ = gettext_lazy("N/A")


class Message(models.Model):
    """
    A message that was either sent or received
    """

    # The type of message
    type = models.IntegerField(choices=MessageType.choices)

    # The actual sender and recipient email
    sender_email = models.EmailField()
    recipient_email = models.EmailField()

    # The name and email as parsed from the 'From' header
    from_name = models.CharField(max_length=255)
    from_email = models.EmailField()

    # A concatenated string of recipients as parsed from the 'To' header(s)
    to = models.TextField()

    # A concatenated string of copies as parsed from the 'CC' header(s)
    cc = models.TextField(blank=True)

    # The subject of the email
    subject = models.CharField(max_length=255)

    # When the message was received
    timestamp = models.DateTimeField()

    # The content of the message in plain text and HTML form
    text = models.TextField()
    html = models.TextField()

    # The message ID and optionally the corresponding message for creating threads
    message_id = models.CharField(max_length=256)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE, blank=True, null=True)

    # The current status of the message as reported by MailGun
    status = models.IntegerField(choices=MessageStatus.choices, null=True)

    def __str__(self):
        return f'<Message pk={self.pk} sender_email="{self.sender_email}" timestamp="{self.timestamp}">'

    def is_older_than_a_day(self):
        """
        Whether the message is older than a day
        """
        difference = timezone.now() - self.timestamp
        return difference.days >= 1

    def get_status(self):
        """
        Convert the status integer to a human readable value
        """
        return MessageStatus(self.status).label if self.status is not None else None

    class Meta:
        ordering = ["-timestamp"]


def upload_to_location(_instance, _filename):
    """
    Generate the path in S3 to store the files
    """
    return path.join("attachments", str(uuid4()))


class Attachment(models.Model):
    """
    An attachment on an conversations email
    """

    # The corresponding email
    message = models.ForeignKey(Message, on_delete=models.CASCADE)

    # The name of the file
    name = models.CharField(max_length=255)

    # The type of the content
    content_type = models.CharField(max_length=129)

    # Whether the attachment was inline
    inline = models.BooleanField()

    # The reference to the attachment content in S3
    # Generates a new UUID for the file to prevent collisions
    content = models.FileField(upload_to=upload_to_location)

    def __str__(self):
        return f'<Attachment name="{self.name}" type="{self.content_type}">'

conversations/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import request
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView

from utils import mail
from .models import Category, Thread

# Format for the HTML email
HTML_EMAIL_FORMAT = (
    '<!doctype html><head><meta name="viewport" content="width=device-width"/>'
    '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>'
    "<title>{subject}</title></head><body>{html}</body></html>"
)


@login_required
def index(request, name: str = None):
    """
    Display the threads for a given category
    """
    # Get the names of all the categories
    categories = Category.objects.values("name").all()
    categories = ["Uncategorized"] + list(map(lambda c: c["name"], categories))

    # Get the category and the threads in it
    if name:
        name = name.title()
        category = Category.objects.filter(name=name).get()
        threads = category.thread_set.filter(
            Q(assignee=request.user) | Q(assignee=None)
        ).all()
    else:
        category = Category(name="Uncategorized", addresses=[])
        threads = Thread.objects.filter(
            Q(assignee=request.user) | Q(assignee=None), category=None
        ).all()

    return render(
        request,
        "conversations/index.html",
        {"threads": threads, "category": category, "categories": categories},
    )


class ThreadView(LoginRequiredMixin, DetailView):
    model = Thread
    template_name = "conversations/thread.html"

    context_object_name = "thread"

    def get_object(self, queryset=None):
        # Get the thread
        thread = super(ThreadView, self).get_object(queryset=queryset)

        # Prevent users that didn't claim a thread from viewing it
        if thread.assignee != self.request.user and thread.assignee is not None:
            messages.error(
                self.request, "This thread has been claimed by someone else!"
            )
            return redirect("conversations:index")

        # Mark it as read
        last_toggled = self.request.session.get("last_toggle_unread")
        if last_toggled != thread.pk:
            thread.unread = False
            thread.save()

        return thread

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context


@login_required
def claim(request, pk):
    """
    Assign a thread to the requester
    """
    thread = get_object_or_404(Thread, pk=pk)

    # Check that it is not already assigned
    if thread.assignee is not None:
        messages.error(
            request,
            f"This thread is already claimed by {'you' if thread.assignee == request.user else 'someone'}",
        )
        return redirect("conversations:thread", pk=pk)

    # Assign to the user
    thread.assignee = request.user
    thread.save()

    messages.success(request, "Successfully claimed this thread!")
    return redirect("conversations:thread", pk=pk)


@login_required
def unclaim(request, pk):
    """
    Remove a thread from the requester
    """
    thread = get_object_or_404(Thread, pk=pk)

    # Check that it is assigned
    if thread.assignee is None:
        messages.error(request, "This thread is already unclaimed!")
        return redirect("conversations:thread", pk=pk)

    # Check that it is assigned to the requester
    if thread.assignee != request.user:
        messages.error(request, "You cannot unclaim someone else's thread!")
        return redirect("conversations:thread", pk=pk)

    # Remove from the user
    thread.assignee = None
    thread.save()

    messages.success(request, "Successfully unclaimed this thread!")
    return redirect("conversations:thread", pk=pk)


@login_required
def toggle_unread(request, pk):
    thread = get_object_or_404(Thread, pk=pk)

    thread.unread = not thread.unread
    thread.save()
    request.session["last_toggle_unread"] = pk

    if thread.unread:
        status = "unread"
    else:
        status = "read"
    messages.success(request, f"Successfully marked this thread as {status}!")
    return redirect("conversations:thread", pk=pk)


@login_required
def change_category(request, pk):
    """
    Change the category of a thread
    """
    # Get the thread
    thread = get_object_or_404(Thread, pk=pk)

    # Check that it is assigned to the requester
    if thread.assignee != request.user and thread.assignee is not None:
        messages.error(request, "You cannot reply to someone else's thread!")
        return redirect("conversations:thread", pk=pk)

    # Get the category
    category_id = request.GET.get("category")
    if category_id is None:
        category = None
    else:
        # Ensure the id is a number
        try:
            category_id = int(category_id)
        except ValueError:
            messages.error(request, "Cannot change to invalid category")
            return redirect("conversations:thread", pk=pk)

        # Find the category
        category = get_object_or_404(Category, pk=category_id)

    # Set the new category
    thread.category = category
    thread.save()

    return redirect("conversations:thread", pk=pk)


@login_required
def reply(request, pk):
    """
    Reply to a thread
    """
    # Get the thread
    thread = get_object_or_404(Thread, pk=pk)

    # Check that it is assigned to the requester
    if thread.assignee != request.user and thread.assignee is not None:
        messages.error(request, "You cannot reply to someone else's thread!")
        return redirect("conversations:thread", pk=pk)

    # Get the last message that was sent that wasn't from an @wafflehacks.tech email
    previous_messages = thread.message_set.all()
    last_message = previous_messages[0]
    for last_message in previous_messages:
        if "wafflehacks.tech" not in last_message.from_email:
            break

    # Render the template on initial request
    if request.method == "GET":
        return render(
            request,
            "conversations/reply.html",
            {"thread": thread, "last_message": last_message, "new_message": False},
        )

    # Get fields from request
    from_name = request.POST.get("name")
    from_email = request.POST.get("email")
    subject = request.POST.get("subject")
    html = request.POST.get("body")
    plaintext = request.POST.get("plaintext")

    # Get all the previous message ids for the References header
    message_ids = "\r\n".join([msg.message_id for msg in previous_messages.reverse()])

    # Queue the message for messages
    is_successful = mail.dispatch_message(
        request,
        from_name,
        from_email,
        f"{last_message.from_name} <{last_message.from_email}>",
        subject,
        html,
        plaintext,
        last_message.message_id,
        message_ids,
    )
    if not is_successful:
        return redirect("conversations:reply", pk=thread.pk)

    messages.success(
        request,
        "Successfully queued your reply for messages! "
        "It will be added below once it is successfully sent.",
    )
    return redirect("conversations:thread", pk=pk)


@login_required
def delete(request, pk):
    """
    Delete the specified message
    """
    # Get the thread
    thread = get_object_or_404(Thread, pk=pk)

    # Check that it is assigned to the requester
    if thread.assignee != request.user and thread.assignee is not None:
        messages.error(request, "You cannot delete someone else's thread!")
        return redirect("conversations:thread", pk=pk)

    # Delete the thread
    thread.delete()

    return redirect("conversations:index")


@login_required
def send(request):
    """
    Send a new message (starts a new thread)
    """
    if request.method == "GET":
        return render(request, "conversations/send.html", {"new_message": True})

    # Get fields from request
    from_name = request.POST.get("name")
    from_email = request.POST.get("email")
    to = request.POST.get("to")
    subject = request.POST.get("subject")
    html = request.POST.get("body")
    plaintext = request.POST.get("plaintext")

    # Queue the message for sending
    is_successful = mail.dispatch_message(
        request, from_name, from_email, to, subject, html, plaintext
    )
    if not is_successful:
        return redirect("conversations:send")

    messages.success(
        request,
        "Successfully queued your message for sending! "
        "It will be added below once it is successfully sent.",
    )
    return redirect("conversations:index")

conversations/templates/conversations/index.html
{% extends 'base.html' %}

{% block title %}Conversations{% endblock %}

{% block content %}
    <div class="card w-100 mb-3">
        <div class="card-body">
            <div class="row text-center">
                <div class="col-md">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">Home</a>
                </div>
                <div class="col-md">
                    <a class="btn btn-outline-success" href="{% url 'conversations:send' %}">New Message</a>
                </div>
            </div>

            <br/>

            <p>
                Below are all the threads, both claimed and unclaimed, in your inbox.
                Open a thread by clicking on it, where you can then view and reply to it.
                Use the tabs below to switch between categories.
                To change a thread's category, open the thread and select the category from the dropdown at the top.
            </p>
        </div>
    </div>

    <div class="card w-100">
        <div class="card-body">
            <ul class="nav nav-tabs">
                {% for c in categories %}
                    <li class="nav-item">
                        <a class="nav-link {% if c == category.name %}active{% endif %}" {% if c == category.name %}aria-current="page"{% endif %} href="{% if c == 'Uncategorized' %}{% url 'conversations:index' %}{% else %}{% url 'conversations:category' c|lower %}{% endif %}">{{ c }}</a>
                    </li>
                {% endfor %}
            </ul>

            <br/>

            <div class="list-group">
                {% for thread in threads %}
                    <a href="{% url 'conversations:thread' thread.pk %}" class="list-group-item list-group-item-action" style="background-color: {% cycle 'white' '#e9e9e9' %}" aria-current="true">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ thread.subject }}</h5>
                            <small>
                                {% if thread.is_older_than_a_day %}
                                    {{ thread.last_updated|date }},
                                {% endif %}
                                {{ thread.last_updated|time:"f A" }}
                                {% if thread.unread %}<span class="badge bg-success">Unread</span>{% endif %}
                            </small>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <span class="badge bg-secondary">From</span>
                                {{ thread.originally_from }}
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <span class="badge bg-primary">To</span>
                                {{ thread.recipient }}
                            </div>
                        </div>
                    </a>
                {% empty %}
                    <div class="card w-100">
                        <div class="card-body">
                            <p>Hooray! You have no messages, check back later!</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

conversations/templates/conversations/reply.html
{% extends 'base.html' %}

{% block title %}Reply to Thread {{ thread.pk }}{% endblock %}

{% block content %}
    <div class="card w-100">
        <div class="card-body">
            <h4 class="card-title">Replying to {{ last_message.from_name }} &lt;{{ last_message.from_email }}&gt;:</h4>
            <p class="card-text">
                Type your reply in the text box below.
                You may be able to use HTML (it hasn't been tested yet), but keep in mind that not all email apps support it.
                For convenience, your email and name are filled in by default, but you can change them to anything you'd like.
                Similarly, the subject is automatically prepended with <code>Re:</code> so you don't have to, but you can still change the subject if you'd like.
            </p>
        </div>
    </div>
    <br/>
    <div class="card w-100">
        <div class="card-body">
            <form action="{% url 'conversations:reply' thread.pk %}" method="post" enctype="multipart/form-data" id="message-form">
                {% include 'messages/message_form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

conversations/templates/conversations/send.html
.{% extends 'base.html' %}

{% block title %}New Message{% endblock %}

{% block content %}
    <div class="card w-100">
        <div class="card-body">
            <h4 class="card-title">New Message:</h4>
            <p class="card-text">
                Type your message, the subject, and who it is to in the text boxes below.
                You may be able to use HTML (it hasn't been tested yet), but keep in mind that not all email apps support it.
                For convenience, your email and name are filled in by default, but you can change them to anything you'd like.
            </p>
            <p class="card-text">
                In the <code>To</code> field, you can either enter just the email or a name and the corresponding email.
                You can send emails to multiple recipients separating each address with a comma.
                <pre>
Email only:         example@test.com
Email with name:    Example Test &lt;example@test.com&gt;
                </pre>
            <br/>
            <b>NOTE:</b> you will need to claim the thread once it is sent as auto-claiming is not yet implemented.
            </p>
        </div>
    </div>
    <br/>
    <div class="card w-100">
        <div class="card-body">
            <form action="{% url 'conversations:send' %}" method="post" enctype="multipart/form-data" id="message-form">
                {% include 'messages/message_form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

conversations/templates/conversations/thread.html
{% extends 'base.html' %}

{% block title %}Thread {{ thread.pk }}{% endblock %}

{% block custom-js %}
    <!-- JQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>

    <!-- Summernote -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-lite.min.js" integrity="sha512-98e5nQTE7pmtZ3xoD5GCVKafmziXDT5WINC91MugFzF57zzBnmvGQl1N70cvdyBSWxjCOC55gq9Zn76MUgtEMQ==" crossorigin="anonymous"></script>
{% endblock %}

{% block custom-css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-lite.min.css" integrity="sha512-wXEyXmtKft9mEiu8LTc3+3BQ95aYbvxgvzH4IzFHOwvGlA14B6zREXD4CRmUPx8r2Z1RVUOXS47bwjsotSlZkQ==" crossorigin="anonymous" />
{% endblock %}

{% block content %}
    <div class="card w-100 h-100">
        <div class="card-body align-self-center mt-1">
            <a class="btn btn-primary" href="{% url 'conversations:reply' thread.pk %}">Reply</a>
            {% if  thread.unread %}
                <a class="btn btn-success" href="{% url 'conversations:toggle_unread' thread.pk %}">Mark Read</a>
            {% else %}
                <a class="btn btn-outline-warning" href="{% url 'conversations:toggle_unread' thread.pk %}">Mark Unread</a>
            {% endif %}
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#change-category-modal">Change Category</button>
            {% if not thread.assignee %}
                <a class="btn btn-success" href="{% url 'conversations:claim' thread.pk %}">Claim</a>
            {% else %}
                <a class="btn btn-outline-warning" href="{% url 'conversations:unclaim' thread.pk %}">Unclaim</a>
            {% endif %}
            <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#delete-modal">
                Delete Thread
            </button>
        </div>
    </div>

    {% for message in thread.message_set.all %}
        <div class="card w-100 mt-3">
            <div class="card-header">
                <div class="row justify-content-between">
                    <div class="col-10">
                        <h5 class="card-header-title">{{ message.subject }}</h5>
                    </div>
                    <div class="col-2">
                        <small>
                            {% if message.status == 0 %}
                                <span class="badge bg-secondary" title="Your message is waiting to be sent...">
                            {% elif message.status == 1 %}
                                <span class="badge bg-success" title="Your message was successfully sent!">
                            {% elif message.status == 2 %}
                                <span class="badge bg-danger" title="Your message could not be sent!">
                            {% else %}
                                <span class="d-none">
                            {% endif %}
                                {{ message.get_status }}</span>
                        </small>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <span class="badge bg-secondary">From</span>
                        {{ message.from_name }} &lt;{{ message.from_email }}&gt;
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <span class="badge bg-primary">To</span>
                        {{ message.to }}
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div id="summernote-{{ message.id }}" class="summernote"></div>
                <script type="text/plain" id="summernote-content-{{ message.id }}">{{ message.html|safe }}</script>
            </div>
            <div class="card-footer">
                {% with attachments=message.attachment_set.all %}
                    {% if attachments|length != 0 %}
                        <ul class="list-group list-group-flush mb-2">
                            {% for attachment in attachments %}
                                <li class="list-group-item rounded-3 my-1">
                                    {% if attachment.inline %}
                                        <span class="badge bg-success">Inline</span>
                                    {% endif %}
                                    <a class="list-group-item-action" target="_blank" href="{{ attachment.content.url }}">
                                        {{ attachment.name }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endwith %}
                <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="collapse" data-bs-target="#view-source-{{ message.pk }}" aria-expanded="false" aria-controls="view-source-{{ message.pk }}">
                    View Source
                </button>
                <div class="collapse" id="view-source-{{ message.pk }}">
                    <pre>

Message ID: {{ message.pk }}
Sender: {{ message.sender_email }}
Recipient: {{ message.recipient_email }}
Received-At: {{ message.timestamp|date:'c' }}

From: {{ message.from_name }} &lt;{{ message.from_email }}&gt;
To: {{ message.to }}
{% if message.cc|length != 0 %}CC: {{ message.cc }}
{% endif %}
Subject: {{ message.subject }}

{{ message.text }}
                    </pre>
                </div>
            </div>
        </div>
    {% endfor %}

    <br/>
    <a class="btn btn-outline-secondary" href="{% if thread.category %}{% url 'conversations:category' thread.category.name|lower %}{% else %}{% url 'conversations:index' %}{% endif %}">Back</a>

    <div class="modal fade" id="delete-modal" tabindex="-1" aria-labelledby="delete-modal-label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="delete-modal-label">Delete Thread</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this thread? This action is <b>irreversible</b>!
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancel</button>
                    <a class="btn btn-outline-danger" href="{% url 'conversations:delete' thread.pk %}">Confirm</a>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="change-category-modal" tabindex="-1" aria-labelledby="change-category-modal-label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="change-category-modal-label">Change Category</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Change the current thread's category:</p>

                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="category" id="category-uncategorized" value="" {% if thread.category.name is None %}checked{% endif %}/>
                        <label class="form-check-label" for="category-uncategorized">Uncategorized</label>
                    </div>
                    {% for category in categories %}
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="category" id="category-{{ category.name|lower }}" value="{{ category.pk }}" {% if thread.category == category %}checked{% endif %}/>
                            <label class="form-check-label" for="category-{{ category.name|lower }}">{{ category.name }}</label>
                        </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-success" id="change-category-submit">Change</button>
                </div>
            </div>
        </div>
    </div>
    <script type="application/javascript">
        const summernote = $(".summernote");

        // Initialize the summernote instances
        summernote.summernote({
            height: 300,
            minHeight: 300,
            tabsize: 2,
            toolbar: []
        });
        summernote.summernote("disable");

        // Add content to each instance
        summernote.each((_, note) => {
            // Get the content
            const id = note.id.substring(11);
            const content = $(`#summernote-content-${id}`).html();

            // Add it to the instance
            $(note).summernote("code", content);
        });

        // Submission handler for changing a thread's category
        $("#change-category-submit").on("click", () => {
            const checked = $('input[name="category"]:checked').val();
            if (checked === "") window.location.href = "{% url 'conversations:change_category' thread.pk %}";
            else window.location.href = "{% url 'conversations:change_category' thread.pk %}?category=" + checked;
        });
    </script>
{% endblock %}