account/urls.py
from django.urls import path

from . import views

app_name = "account"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("oauth/start", views.start_login, name="oauth_start"),
    path("oauth/authorize", views.finish_login, name="oauth_finish"),
    path("settings", views.settings, name="settings"),
    path("logout", views.logout_view, name="logout"),
]

mailgunner/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from . import views

urlpatterns = [
    # Home page
    path("", views.index, name="index"),
    # user authentication
    path("account/", include("account.urls")),
    # conversations mail
    path("conversations/", include("conversations.urls")),
    # schedule mail
    path("schedule/", include("schedule.urls")),
    # Routes from other packages
    path("admin/", admin.site.urls),
    re_path(r"^webhooks/", include("anymail.urls")),
]

schedule/urls.py
from django.urls import path

from . import views

app_name = "schedule"
urlpatterns = [
    path("", views.QueuedView.as_view(), name="queued"),
    path("sent", views.SentView.as_view(), name="sent"),
    path("new", views.new, name="new"),
    path("messages/<int:pk>", views.MessageView.as_view(), name="message"),
    path("messages/<int:pk>/delete", views.delete, name="delete"),
]

schedule/models.py
from django.db import models
from django.utils import timezone
from os import path
from uuid import uuid4


class Message(models.Model):
    """
    A message that is scheduled to be sent at sometime in the future
    """

    # Who the email is from
    from_name = models.CharField(max_length=255)
    from_email = models.EmailField()

    # Who the email should be sent to
    to = models.TextField()

    # The subject of the email
    subject = models.CharField(max_length=255)

    # The contents of the message in plain text and HTML
    text = models.TextField()
    html = models.TextField()

    # When the message should be sent
    send_at = models.DateTimeField()

    def __str__(self):
        return f'<ScheduledMessage pk={self.pk} from="{self.from_name} <{self.from_email}>" send_at={self.send_at}>'

    def was_sent(self):
        """
        Whether the message has already been sent
        """
        return timezone.now() >= self.send_at

    class Meta:
        ordering = ["send_at"]


def upload_to_location(_instance, _filename):
    """
    Generate the path in S3 to store the files
    """
    return path.join("schedule", str(uuid4()))


class Attachment(models.Model):
    """
    An attachment on a message
    """

    # The corresponding message
    message = models.ForeignKey(Message, on_delete=models.CASCADE)

    # The name of the file
    name = models.CharField(max_length=255)

    # The type of the content
    content_type = models.CharField(max_length=129)

    # Whether the attachment was inline
    inline = models.BooleanField()

    # The reference to the attachment content in S3
    # Generates a new UUID for the file to prevent collisions
    content = models.FileField(upload_to=upload_to_location)

schedule/views.py
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.uploadedfile import TemporaryUploadedFile
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views.generic import DetailView, ListView
from email.utils import getaddresses
from pathlib import Path

from utils import mail
from .models import Message
from .tasks import queue_message

DATETIME_FORMAT = "%Y-%m-%d %H:%M"


class BaseIndexView(LoginRequiredMixin, ListView):
    model = Message
    template_name = "schedule/index.html"

    context_object_name = "scheduled"


class QueuedView(BaseIndexView):
    current_tab = "queued"
    description = "are queued to be sent"

    def get_queryset(self):
        return Message.objects.filter(send_at__gte=timezone.now())


class SentView(BaseIndexView):
    current_tab = "sent"
    description = "have been sent"

    def get_queryset(self):
        return Message.objects.order_by("-send_at").filter(send_at__lte=timezone.now())


@login_required
def new(request):
    """
    Schedule a new message to be sent
    """
    if request.method == "GET":
        return render(request, "schedule/send.html", {"new_message": True})

    # Get fields from request
    from_name = request.POST.get("name")
    from_email = request.POST.get("email")
    to = request.POST.get("to")
    subject = request.POST.get("subject")
    send_at = request.POST.get("send_at")
    html = request.POST.get("body")
    plaintext = request.POST.get("plaintext")

    # Ensure all the fields are present
    if not mail.validate_fields(
        request, from_name, from_email, to, subject, html, plaintext
    ):
        return redirect("schedule:new")
    if send_at is None:
        messages.error(request, "Your message must have a date and time to be sent at")

    # Build the mime message to ensure consistency
    mime_message = mail.build_message(
        request, from_name, from_email, to, subject, html, plaintext
    )

    # Parse the timestamp and make it timezone aware
    parsed_send_at = datetime.strptime(send_at, DATETIME_FORMAT)
    parsed_send_at = timezone.make_aware(parsed_send_at)

    # Save the scheduled message to the database
    [(parsed_from_name, parsed_from_email)] = getaddresses([mime_message.from_email])
    message = Message(
        from_name=parsed_from_name,
        from_email=parsed_from_email,
        to=to,
        subject=mime_message.subject,
        send_at=parsed_send_at,
        text=plaintext,
        html=html,
    )
    message.save()

    # Extract any attachments
    for attachment in mime_message.attachments:
        # Extract the mime details
        name, content, mime = attachment

        # Get only the filepath
        sanitized_path = Path(name).name

        # Create a tempfile to be uploaded
        temp = TemporaryUploadedFile(name, mime, len(content), "utf-8")
        if type(content) == str:
            temp.write(content.encode())
        else:
            temp.write(content)

        message.attachment_set.create(
            name=sanitized_path, content_type=mime, inline=False, content=temp
        )

    # Queue the message for sending later
    queue_message.apply_async((message.id,), eta=message.send_at)

    return redirect("schedule:queued")


class MessageView(LoginRequiredMixin, DetailView):
    model = Message
    template_name = "schedule/message.html"

    context_object_name = "message"


@login_required
def delete(request, pk):
    """
    Delete the specified message
    """
    # Get the message
    message = get_object_or_404(Message, pk=pk)

    # Delete it
    message.delete()

    # Redirect based on whether it was sent or not
    if message.was_sent():
        return redirect("schedule:sent")
    else:
        return redirect("schedule:queued")

schedule/templates/schedule/index.html
{% extends 'base.html' %}

{% block title %}Schedule Mail{% endblock %}

{% block content %}
    <div class="card w-100 mb-3">
        <div class="card-body">
            <div class="row text-center">
                <div class="col-md">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">Home</a>
                </div>
                <div class="col-md">
                    <a class="btn btn-outline-success" href="{% url 'schedule:new' %}">Schedule Message</a>
                </div>
            </div>

            <br/>

            <p>
                Below are all the messages that {{ view.description }}.
                Use the tabs below to switch between sent and queued messages.
                You can edit a message up until the time it is scheduled to be sent.
            </p>
        </div>
    </div>

    <div class="card w-100">
        <div class="card-body">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link {% if view.current_tab == "queued" %}active{% endif %}" {% if view.current_tab == "queued" %}aria-current="page"{% endif %} href="{% url 'schedule:queued' %}">Queued</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view.current_tab == "sent" %}active{% endif %}" {% if view.current_tab == "sent" %}aria-current="page"{% endif %} href="{% url 'schedule:sent' %}">Sent</a>
                </li>
            </ul>

            <br/>

            <div class="list-group">
                {% for message in scheduled %}
                    <a href="{% url 'schedule:message' message.pk %}" class="list-group-item list-group-item-action" style="background-color: {% cycle 'white' '#e9e9e9' %}" aria-current="true">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ message.subject }}</h5>
                            <small>
                                <span class="badge {% if view.current_tab == 'queued' %}bg-secondary{% else %}bg-success{% endif %}">{{ view.current_tab|capfirst }}</span>
                                {{ message.send_at|date }}
                                {{ message.send_at|time:"f A" }}
                            </small>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <span class="badge bg-secondary">From</span>
                                {{ message.from_name }} &lt;{{ message.from_email }}&gt;
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <span class="badge bg-primary">To</span>
                                {{ message.to }}
                            </div>
                        </div>
                    </a>
                {% empty %}
                    <div class="card w-100">
                        <div class="card-body">
                            <p>No {{ view.current_tab }} messages yet...</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

schedule/templates/schedule/message.html
{% extends "base.html" %}

{% block title %}Scheduled Message {{ message.pk }}{% endblock %}

{% block custom-js %}
    <!-- JQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>

    <!-- Summernote -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-lite.min.js" integrity="sha512-98e5nQTE7pmtZ3xoD5GCVKafmziXDT5WINC91MugFzF57zzBnmvGQl1N70cvdyBSWxjCOC55gq9Zn76MUgtEMQ==" crossorigin="anonymous"></script>
{% endblock %}

{% block custom-css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-lite.min.css" integrity="sha512-wXEyXmtKft9mEiu8LTc3+3BQ95aYbvxgvzH4IzFHOwvGlA14B6zREXD4CRmUPx8r2Z1RVUOXS47bwjsotSlZkQ==" crossorigin="anonymous" />
{% endblock %}

{% block content %}
    <div class="card w-100 h-100">
        <div class="card-body align-self-center mt-1">
            <a class="btn btn-outline-secondary" href="{% if message.was_sent %}{% url 'schedule:sent' %}{% else %}{% url 'schedule:queued' %}{% endif %}">Back</a>
            <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#delete-modal">
                Delete
            </button>
        </div>
    </div>

    <div class="card w-100 mt-3">
        <div class="card-header">
            <div class="row justify-content-between">
                <div class="col-9">
                    <h5 class="card-header-title">{{ message.subject }}</h5>
                </div>
                <div class="col-3">
                    {% if message.was_sent %}
                        <span class="badge bg-success">Sent at</span>
                    {% else %}
                        <span class="badge bg-secondary">Queued for</span>
                    {% endif %}
                    {{ message.send_at|date }}
                    {{ message.send_at|time:"f A" }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <span class="badge bg-secondary">From</span>
                    {{ message.from_name }} &lt;{{ message.from_email }}&gt;
                </div>
                <div class="col-md-6 col-sm-12">
                    <span class="badge bg-primary">To</span>
                    {{ message.to }}
                </div>
            </div>
        </div>
        <div class="card-body">
            <div id="summernote-{{ message.id }}" class="summernote"></div>
            <script type="text/plain" id="summernote-content-{{ message.id }}">{{ message.html|safe }}</script>
        </div>
        {% with attachments=message.attachment_set.all %}
            {% if attachments|length != 0 %}
                <div class="card-footer">
                    <ul class="list-group list-group-flush">
                        {% for attachment in attachments %}
                            <li class="list-group-item">
                                {% if attachment.inline %}
                                    <span class="badge bg-success">Inline</span>
                                {% endif %}
                                <a class="list-group-item-action" target="_blank" href="{{ attachment.content.url }}">
                                    {{ attachment.name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endwith %}
    </div>

    <div class="modal fade" id="delete-modal" tabindex="-1" aria-labelledby="delete-modal-label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="delete-modal-label">Delete Message</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this message?
                    {% if not message.was_sent %}
                        This message will not no longer be sent once deleted.
                    {% endif %}
                    This action is <b>irreversible</b>!
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancel</button>
                    <a class="btn btn-outline-danger" href="{% url 'schedule:delete' message.pk %}">Confirm</a>
                </div>
            </div>
        </div>
    </div>

    <script type="application/javascript">
        const summernote = $(".summernote");

        // Initialize the summernote instance
        summernote.summernote({
            height: 300,
            minHeight: 300,
            tabsize: 2,
            toolbar: []
        });
        summernote.summernote("disable");

        // Add content to each instance
        summernote.each((_, note) => {
            // Get the content
            const id = note.id.substring(11);
            const content = $(`#summernote-content-${id}`).html();

            // Add it to the instance
            $(note).summernote("code", content);
        });
    </script>
{% endblock %}

schedule/templates/schedule/message_form.html
{% extends "messages/message_form.html" %}
{% load static %}

{% block extra_resources %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.9/flatpickr.min.css" integrity="sha512-OtwMKauYE8gmoXusoKzA/wzQoh7WThXJcJVkA29fHP58hBF7osfY0WLCIZbwkeL9OgRCxtAfy17Pn3mndQ4PZQ==" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.9/flatpickr.min.js" integrity="sha512-+ruHlyki4CepPr07VklkX/KM5NXdD16K1xVwSva5VqOVbsotyCQVKEwdQ1tAeo3UkHCXfSMtKU/mZpKjYqkxZA==" crossorigin="anonymous"></script>

    <script src="{% static 'schedule/flatpickr.js' %}"></script>
{% endblock %}

{% block extra_fields %}
    <div class="row g-2 mb-3">
        <div class="w-50">
            <label for="datetime-picker" class="mb-1">Send At</label>
            <input type="text" id="datetime-picker" name="send_at" placeholder="Select date and time..." required="required"/>
            <small class="text-muted"><b>NOTE:</b> Time is in PST</small>
        </div>
    </div>
{% endblock %}

schedule/templates/schedule/send.html
{% extends "base.html" %}
{% load static %}

{% block title %}Schedule Message{% endblock %}

{% block content %}
    <div class="card w-100">
        <div class="card-body">
            <h4 class="card-title">New Scheduled Message:</h4>
            <p class="card-text">
                Type your message, the subject, and who it is to in the text boxes below.
                You can use all the features of the text editor, but keep in mind that not all email apps will display it the same way.
                For convenience, your email and name are filled in by default, but you can change them to anything you'd like.
            </p>
            <p class="card-text">
                In the <code>To</code> field, you can either enter just the email or a name and the corresponding email.
                You can send emails to multiple recipients by separating each address with a comma.
                <pre>
    Email only:         example@test.com
    Email with name:    Example Test &lt;example@test.com&gt;
                </pre>
            </p>
        </div>
    </div>

    <br/>
    <div class="card w-100">
        <div class="card-body">
            <form action="{% url 'schedule:new' %}" method="post" enctype="multipart/form-data" id="message-form">
                {% include "schedule/message_form.html" %}
            </form>
        </div>
    </div>
{% endblock %}